First pass at gpu stats for macs
wandb/client pull request #1616
Opened 2020-12-16 19:35 UTC by vanpelt

2020-12-16 20:23 UTC, farizrahman4u reviewed
Do we *really* need to check in C code in client repo? Can we download the binary during install?

2020-12-16 20:47 UTC, vanpelt commented
> Do we _really_ need to check in C code in client repo? Can we download the binary during install?
> 
> Edit: NVM, just saw that you are bundling the binary in `vendor/` (I assumed user had to build following the readme). All good.

Yeah, right now I just build manually if I need to cur a new binary.  I have an apple developer account so we do code signing and all that fun stuff.  Figured we want to have the actual source code checked in and putting it here could help other users that want to access this information from Mac OS.

2021-01-04 18:56 UTC, raubitsj requested changes

2021-01-04 18:56 UTC, raubitsj commented on pyproject.toml
> +| tests/*\.pyi?$
This breaks black formatting/checking as it doesnt handle recursive dirs

2021-01-04 18:58 UTC, raubitsj reviewed
otherwise, looks good

2021-01-04 22:47 UTC, raubitsj commented on pyproject.toml
> +| tests/*\.pyi?$
fixed this in your branch

2021-01-04 23:01 UTC, raubitsj approved these changes

2021-01-04 23:01 UTC, merged