Console redirect fixes
wandb/client pull request #1633
Opened 2020-12-21 13:18 UTC by farizrahman4u

2021-01-19 16:42 UTC, raubitsj requested changes
Regression fails to run on this branch.  All runs fail with:
```
Traceback (most recent call last):
  File "mnist_cnn.py", line 15, in <module>
    import wandb
  File "/home/jeff/.pyenv/versions/v368/lib/python3.6/site-packages/wandb/__init__.py", line 32, in <module>
    from wandb.errors.term import termsetup, termlog, termerror, termwarn
  File "/home/jeff/.pyenv/versions/v368/lib/python3.6/site-packages/wandb/errors/term.py", line 2, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

2021-01-19 16:42 UTC, raubitsj commented on requirements.txt
> +git+https://github.com/selectel/pyte#egg=pyte
I don't think this is a good idea, Lets chat offline about it.

2021-01-25 17:24 UTC, vanpelt commented on tests/test_redir.py
> +        assert len(o) in (epochs * 2, epochs * 2 + 1)  # Allow 1 offs
Curious what the "1 off" comes from?

2021-01-25 17:24 UTC, vanpelt commented on wandb/sdk/lib/redirect.py
> +                pass  # TODO(frz): partial unicode character?
This is a BEAST.  It's looking good, let's add some doc strings to describe what these various classes and methods are doing.

2021-01-25 18:08 UTC, farizrahman4u commented on tests/test_redir.py
> +        assert len(o) in (epochs * 2, epochs * 2 + 1)  # Allow 1 offs
Windows vs linux

2021-01-26 16:51 UTC, raubitsj commented
We are ignoring the codecov/patch warnings for this PR as console is very difficult to cover in the circle environment.

2021-01-26 17:47 UTC, raubitsj reviewed
Can you pull master into this branch also.

2021-01-26 17:47 UTC, raubitsj commented on wandb/sdk/wandb_run.py
> +class CRDedupedFile(WriteSerializingFile):
CRDedupedFile seems out of place. can you find somewhere else to put this?
maybe in lib/something
along with WriteSerializingFile maybe?

2021-02-24 00:51 UTC, raubitsj approved these changes
Wow, lots of great stuff in here.  merging now.

2021-02-24 00:53 UTC, merged