[WB-4612] Disable login in disabled mode
wandb/client pull request #1842
Opened 2021-02-15 06:49 UTC by farizrahman4u

https://wandb.atlassian.net/browse/WB-4612

Description
-----------

What does the PR do? - disables wandb login in disabled mode

Testing
-------

How was this PR tested?- manually

2021-02-16 01:20 UTC, vanpelt approved these changes

2021-02-16 01:22 UTC, vanpelt commented
This should be really easy to test, kinda suprised we don't have any explicity wandb.login tests currently...

2021-02-16 02:41 UTC, raubitsj requested changes

2021-02-16 02:41 UTC, raubitsj commented on wandb/sdk/wandb_login.py
> +    if wandb.setup()._settings.mode == "disabled":
More precise would be:
```
if wandb.setup()._settings._noop:
    return True
```

2021-02-17 19:19 UTC, raubitsj approved these changes
great

2021-02-17 19:53 UTC, merged