[WB-4545]: Made config append-only when resuming
wandb/client pull request #1857
Opened 2021-02-18 02:34 UTC by tssweeney

https://wandb.atlassian.net/browse/WB-4545

Description
-----------

What does the PR do?

Users are confused with the behavior of config when resuming. Current behavior is to completely overwrite the existing config with the config with the latest resume. In slack, we decided that an alternative is to treat configs as "append only", so runs which are resuming a prior run can only add new keys to the config. Under the hood, the run.config will be updated with the correct prior values even if keys are passed with new values in the latest run.

Note: this feels a bit odd, so want to double check that this is what we want cc @raubitsj + @vanpelt 

Testing
-------

How was this PR tested?

Added a unit test

2021-02-18 03:03 UTC, raubitsj commented
Seems right to me

Please add a TODO to let the user know that their config values were ignored because they were already set..  it isnt trivial to do that yet, but it will be soon.

2021-02-18 17:19 UTC, vanpelt approved these changes

2021-02-19 16:38 UTC, raubitsj requested changes
The windows test is failing consistently on a test related to this change.  We need to debug it before merging.  I can help next week if needed.

2021-02-19 16:41 UTC, tssweeney commented
> The windows test is failing consistently on a test related to this change. We need to debug it before merging. I can help next week if needed.

Yeah, am not sure what is going on, but will certainly keep debugging and get it passing before merge. Thanks for offering to help (:

2022-02-18 18:32 UTC, closed without merging