Artifacts/checkout
wandb/client pull request #1901
Opened 2021-02-25 17:15 UTC by annirudh

https://wandb.atlassian.net/browse/WB-4604

Description
-----------

Adds a new `checkout()` artifact API that mimics `git checkout` by replacing the contents of a specified directory with the contents of the artifact.

Testing
-------

- Ran loadtest with the checkout option (verify now errors if there are mismatched files)

2021-02-25 17:58 UTC, vanpelt requested changes
This should be pretty easy to test.  See, `wandb_artifacts_test.py`

2021-02-25 18:28 UTC, annirudh commented
> This should be pretty easy to test. See, `wandb_artifacts_test.py`

@vanpelt Added!

2021-02-25 19:01 UTC, vanpelt commented
Nice, deciphering the [code cov report](https://app.codecov.io/gh/wandb/client/compare/1901/diff) can be a bit of a mystery.  We aggressively try to ensure anything in sdk stays covered.  I *think adding a test for [this case](https://app.codecov.io/gh/wandb/client/compare/1901/diff#D3L453) will fix the current codecov check.  @raubitsj seems like testing [this case](https://app.codecov.io/gh/wandb/client/compare/1901/diff#D4L589) isn't something we should need...

2021-02-26 06:39 UTC, tssweeney approved these changes
LGTM - awesome add

2021-02-26 06:39 UTC, tssweeney commented on wandb/apis/public.py
> +                except KeyError:
Nit: this block is shared with the checkout method above - could be refactored to accept a callback when there is a KeyError.

2021-02-26 19:57 UTC, vanpelt approved these changes

2021-02-26 21:08 UTC, merged