[WB-6233] increase timeout for public api requests to 50s
wandb/client pull request #2517
Opened 2021-08-08 04:06 UTC by dannygoldstein

https://wandb.atlassian.net/browse/WB-6233

Description
-----------
This PR increases the timeout on the public api to 50s to match the frontend. 

Release Notes
-------------

Below, please enter user-facing release notes as one or more bullet points.
If your change is not user-visible, write `NO RELEASE NOTES` instead, with no bullet points.

------------- BEGIN RELEASE NOTES ------------------
Increase timeout on public API to 50s 
------------- END RELEASE NOTES --------------------

2021-08-09 18:17 UTC, raubitsj reviewed
Missing a testing section.

What is the history of this 9s seems pretty specific, @vanpelt: do you have any history on this?

2021-08-09 18:30 UTC, vanpelt commented
@raubitsj I'm a little hazy on the original thinking.  I wouldn't be surprised if I just thought requests that took longer than 10s were a problem and if my jupyter or shell is hanging for longer than 10s I'm getting frustrated.  Why 9 instead of 10?  No clue 😭 

In general I think it would be a really good idea to keep all requests under 10s by limiting the page size / addressing performance issues.  @dannygoldstein what are the specific requests that are timing out which prompted this change?

2021-08-09 18:41 UTC, dannygoldstein commented
@vanpelt the motivation is described in this jira ticket: https://wandb.atlassian.net/browse/WB-6233

2021-08-20 03:20 UTC, dannygoldstein commented
I sidestepped the issue of choosing a timeout for the user and added a warning explaining how the user can set the timeout to their liking

2021-08-20 03:48 UTC, vanpelt requested changes
Looks good.  Ideally we would tame that stacktrace, so much useless information in it.

Some of our users won't know what "Set WANDB_HTTP_TIMEOUT" means.  It also won't work in interactive contexts because the environment is read when the module is first imported.  This would also set the timeout globally which is unfortunate.  I think a cleaner approach would be having the Api class accept a timeout keyword argument that defaults to the class timeout, i.e.

```
api = wandb.Api(timeout=30)
```

2021-08-20 04:54 UTC, dannygoldstein commented
@vanpelt warnings now look like 

```
wandb: WARNING A graphql request initiated by the public wandb API timed out (timeout=1 sec). Create a new API with an integer timeout larger than 1, e.g., `api = wandb.Api(timeout=11)` to increase the graphql timeout.
wandb: WARNING A graphql request initiated by the public wandb API timed out (timeout=1 sec). Create a new API with an integer timeout larger than 1, e.g., `api = wandb.Api(timeout=11)` to increase the graphql timeout.
wandb: WARNING A graphql request initiated by the public wandb API timed out (timeout=1 sec). Create a new API with an integer timeout larger than 1, e.g., `api = wandb.Api(timeout=11)` to increase the graphql timeout.
Retry attempt failed:
```

2021-08-20 17:42 UTC, vanpelt approved these changes
👍

2021-08-20 17:43 UTC, merged